# Generated by Django 3.2.5 on 2021-11-23 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lost_Article',
            new_name='LostArticle',
        ),
    ]
