version: 2.1

orbs:
    aws-ecr: circleci/aws-ecr@6.1.0
    aws-ecs: circleci/aws-ecs@0.0.8

workflows:
    # build_and_push_imageという名前のworkflowを定義
    build_and_push_image:
        # workflowで実行するjobの順番を定義
        jobs:
        - aws-ecr/build-and-push-image:
            region: AWS_REGION
            account-url: AWS_ECR_ACCOUNT_URL
            repo: 'mission-tools-django'
            tag: "${CIRCLE_SHA1}"
        - aws-ecs/deploy-service-update:
            requires:
                - aws-ecr/build-and-push-image
            family: 'mission_tools_task'
            cluster-name: 'Studio-Mission-Tools'
            service-name: 'Studoi-Mission-Tools-API'
            container-image-name-updates: 'container=testserverContainer,tag=${CIRCLE_SHA1}'